Cargo.lock, Cargo.toml, src/lookup.rs, src/main.rs, src/utils.rs
This implements [documentLink](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentLink), which returns a list of linked documents.
Basically it finds all `Value::Path`s and checks if they exist and are a file. If so it produces a DocumentLink. This exludes `NIX_PATH` links. E.g. in VS Code this enables e.g. ctrl-clicking a path and navigating to the respective file.
First commit is just a `cargo fmt` run.
=> Implement documentLink request

default.nix, flake-compat.nix, shell.nix
This pins the version to the latest commit, and checks the hash for it.
Fixes #16.
=> Pin flake-compat version

README.md
Add an example to README.md using eglot to connect rnix-lsp with emacs
=> Add eglot to list of emacs programs

src/lookup.rs, src/main.rs, src/utils.rs
When I write `builtins.`, it wasn't possible until now to list all
attributes in `builtins` (or any other indexed attr-set).
This happened because in that case `utils::ident_at` found `NODE_SELECT`
for the current token (i.e. `TOKEN_DOT`) and not `NODE_IDENT`. This
patch handles the case where `NODE_SELECT` is the current token and
searches for the last `NODE_IDENT`.
cc @jD91mZM2
=> Allow dot-completion for attributes

src/utils.rs
__Note:__ this is based on the `bump-rnix` branch and shouldn't be merged until that is merged to master.
cc @jD91mZM2
=> Add `var` from `{ a, b, c }@var` to scope

src/main.rs
Seems like `vscode-languageserver-node` also does it like that.
I also noticed that `handle_request` always returns `Ok(())`, so I simplified the type.
=> Respond to unhandled methods with MethodNotFound

Cargo.lock, Cargo.toml, src/lookup.rs, src/main.rs
__Note:__ this isn't completed ready yet:
-----
A hidden feature of Nix 2.4+ (a.k.a. `nixUnstable`) is `nix
__dump-builtins` which returns a JSON giving details about built in
functions.
This change basically does the following things:
* It checks whether Nix 2.4 is available on `$PATH`[1]. In that case
built-in functions are retrieved via `nix __dump-builtins`[2].
If not, the hard-coded list of builtins is used as a fallback.
* If builtins can be retrieved from Nix, the following additional things
are added to `CompletionItem`:
* The `documentation`[3] field containing markdown documentation for the
function is added. This will be shown in editors as one is used to
it from e.g. doc-block comments in other languages.
* A very basic parameter info is provided. E.g. for …
=> Enhance completion details for builtins if Nix 2.4 is available

src/main.rs, src/utils.rs
With incremental parsing, the editor only sends a "diff" of what has
changed rather than the full file. For instance, it's pretty pointless
to send all of `all-packages.nix` from `nixpkgs` for a single-letter
change.
Given the benchmark of `rnix-parser`[1] it doesn't seem as the parsing
itself is the bottleneck a few people have reported[2], so this change
only replaces affected lines and re-parses everything using
`rnix-parser`.
While the current change seems usable on local tests, it has (at
least) two known issues:
* As soon as you type `inherit`, the LSP stalls and it seems it's due to
`rnix-parser` and steadily allocates more memory according to
`strace(1)`. I confirmed that it's indeed a problem of `rnix-parser`
by creating a file with `{ inherit` as content and the LSP refuses to …
=> Enable incremental parsing via the LSP protocol

src/main.rs
Fixes #42. This also adds handling for VSCode's multi-cursor feature, which previously caused the document to go out-of-sync.
=> simplify incremental edit handling

flake.nix, src/lookup.rs
Please note that this currently requires `nixUnstable` for a basic test
of the `nix __dump-builtins`-based completion.
=> Implement a few test-cases for `lookup::scope_for_ident()`

src/main.rs
In a few files I got some syntax errors when modifying their contents.
An example is `<nixpkgs/lib/generators.nix>`[1] with the following
contents in the multi-line comment at the top:
> [...]
> * `config-attrs` are “holes” in the generators
> [...]
These multi-byte quotes confuse the LSP because the LSP itself doesn't
care about the byte offsets itself, but provides character positions in
incremental updates[2]. To quote the specification:
> So a string of the form a𐐀b the character offset of the character a is 0,
> the character offset of 𐐀 is 1 and the character offset of b is 3 since 𐐀 is
> represented using two code units in UTF-16.
However, the actual length (in bytes) of the UTF-16 character from above is
`4`, so a byte-aware offset would be wrong. Unfortunately, `match_indices()` …
=> Fix bogus syntax errors in Nix expressions containing multi-byte characters

.github/workflows/test.yml, Cargo.lock, Cargo.toml, flake-compat.nix, flake.lock, flake.nix, src/main.rs, src/utils.rs
This hopefully fixes the memory leak from https://github.com/nix-community/rnix-lsp/issues/33. Please refer to the commit messages for further details.
Please note that I only did some brief tests. I'd like to run this on my setup for a few days before merging this. Further testers are of course fairly welcome, so we can hopefully find out if my theory regarding #33 is correct :)
=> Dependency updates

Cargo.lock, Cargo.toml, src/lookup.rs, src/tests.rs
* Add testcase for scope-imports in `lookup.rs`. From my PoV this will remain relevant with the evaluator since the underlying logic (navigating through the AST to find actual scopes).
* Added some integration tests + some structure to easily implement more.
=> Enhance testsuite

.github/workflows/test.yml
With this we're seeing more information on why something broke.
=> GHA: add `-L` to `nix build`

src/value.rs
Currently, attribute sets are formatted with a trailing newline (in addition to the one added in [`format_markdown`](https://github.com/nix-community/rnix-lsp/blob/9462b0d20325a06f7e43b5a0469ec2c92e60f5fe/src/value.rs#L84)).
This adds an unnecessary blank line to the hover preview, which looks strange and is inconsistent with how other types are displayed.
This bug was introduced by me in #55.
=> remove leading newline from attr set's fmt::Display

src/lookup.rs
~I will try to reproduce the issue on a second Mac and fix it in this PR~
This PR identifies an assertion that seems to fail on Mac OS, and moves it into a new test. This new test is not run on Mac OS.
Thanks!
----------------
I am not sure why this only occurs on my machine
```
'assertion failed: val.1.get(\"abort\").unwrap().documentation.is_some()', src/lookup.rs:318:9
```
and not on Mac OS CI:
https://github.com/nix-community/rnix-lsp/runs/4346460608?check_suite_focus=true#step:4:575
A test fails on my Mac, which blocks 
```
nix-env -i -f https://github.com/nix-community/rnix-lsp/archive/master.tar.gz
```
The work-around is to disable the test or the failing assertion in the test and install `rnix-lsp` from that.
https://github.com/nix-community/rnix-lsp/issues/60
=> disable assertion in test to fix Mac OS installation

README.md
This PR removes the `$` prompt symbol from the installation snippet. Now the snippet can be copied and used as-is.
=> improve command copying from readme

Cargo.lock, Cargo.toml, flake.lock, flake.nix, src/parse.rs
* Updated the `rnix` dependency to 0.10.1 & fixed compilation errors.
* Updated `nixpkgs-fmt` to a tag `v1.2.0-rnix-0.10`[1]. I explicitly
decided against using `master` as the formatting results are slightly
different to the results of v1.2.0 and we should remain consistent to
what `pkgs.nixpkgs-fmt` would do.
* Switched to a custom fork of `naersk` to keep the build evaluating[2].
[1] https://github.com/Ma27/nixpkgs-fmt/releases/tag/v1.2.0-rnix-0.10
[2] https://github.com/nix-community/naersk/pull/219
I'd cherry-pick this commit on top of `0.2.1` and then publish `0.2.2` to get Nix 2.4 support out.
=> Bump `rnix` to `0.10.1`

flake.lock, flake.nix, src/lookup.rs
Bump `nixpkgs` to 21.11 since 21.05 is dead. Also, the `nixUnstable` from 21.05 doesn't seem to build on Darwin.
see #71 
cc @DieracDelta
=> flake: Bump `nixpkgs` & `flake-utils`

flake.nix
This pull request unpins the version of Nix used as a `checkInput` for the flake's default package. I assume `nix_2_4` was necessary in the past, but there doesn't seem to be any issue with using plain old `pkgs.nix` with the flake's current version of `nixpkgs`.
If there's a reason it should stay as `nix_2_4`, let me know! I've been having quite the time trying to override things so `nix_2_4` doesn't get evaluated, because an error is thrown as soon as it does, and I haven't managed to find something that works yet, so I think some kind of change will be necessary to get this working with nixpkgs-unstable either way.
Closes #92.
=> Unpin the version of Nix used as a checkInput

Cargo.lock, Cargo.toml, src/error.rs, src/main.rs, src/parse.rs, src/static_analysis.rs, src/tests.rs
find at least as much stuff as nix-instantiate --parse-only
currently not very useful because rnix-lsp cannot parse let .. in nor lambda constructs, and they are present in nearly every file.
=> error diagnostics for unbound identifiers

src/lookup.rs
This pull request fixes the version detection regex used when loading the builtins using the nix command so that it doesn't assume that major and minor versions are limited to single digits.
Actually resolves #92, since the command in question there still fails after #93, except it's failing due to `lookup::tests::test_provide_builtins_non_mac` failing since nix 2.10.3's version breaks the current regex.
I also have a more in-depth overhaul of `load_builtins` at https://github.com/mtoohey31/rnix-lsp/tree/fix/dump-builtins-compat-alternate with better error checking that tries the command regardless of version so we don't have to rely on a brittle regex, but I'd be fine with either of the two branches being merged.
=> fix: update Nix version detection regex for loading builtins

src/eval.rs, src/tests.rs
Before:
this happens for >= 3 instances of a
=> fix attrset merging for >= 3 instances

README.md
Add instructions for doom emacs users
Resolves #97
=> :pencil: `docs` add doom integration instructions

flake.nix
fix the rust-analyzer extension in vscode
error was
> rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml ... Is rust-src installed?
based on
https://discourse.nixos.org/t/rust-src-not-found-and-other-misadventures-of-developing-rust-on-nixos/11570/2
=> fix devShell for rust-analyzer
